# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-47ea0d0b613bb952adef11f47bf1699582e2058738f0f514d399e1ef07381a67}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-47ea0d0b613bb952adef11f47bf1699582e2058738f0f514d399e1ef07381a67}
